#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

from testlib import *

class TestRoles(MachineCase):
    def testBasic(self):
        m = self.machine
        b = self.browser

        # Create a user without any role
        m.execute("useradd user -c 'User' || true")
        m.execute("echo foobar | passwd --stdin user")

        # HACK - https://bugzilla.redhat.com/show_bug.cgi?id=1225957
        #
        # We compensate for the GFileMonitor bug by periodically
        # triggering them forcefully in the background.
        #
        # XXX - This is terrible and we should try hard to fix the
        # bug before merge.
        #
        # XXX - there is a race because of the two copies
        #
        if self.machine.os == "fedora-rawhide":
            self.machine.spawn("while true; do sleep 2; cp /etc/group /tmp/xxx && cp /tmp/xxx /etc/group; done", "passwd-trigger.log")

        self.start_cockpit()

        def login(user, password):
            b.set_val("#login-user-input", user)
            b.set_val("#login-password-input", password)
            b.click('#login-button')

        # login
        b.open("server", href="/system/host")
        b.wait_visible("#login")
        login("user", "foobar")
        b.expect_reload()
        b.enter_page("server")
        b.switch_to_top()
        b.wait_text('#content-user-name', 'User')

        # HACK: Logging in as "user" will try to write to
        # /var/lib/cockpit/, but this will fail.
        # https://github.com/cockpit-project/cockpit/issues/1248
        #
        self.allow_journal_messages(".*Failed to create file '/var/lib/cockpit/.*': Permission denied")

        # Try to change its own name
        b.click('#content-user-name')
        b.click('#go-account')
        b.enter_page("account")

        b.wait_text("#account-user-name", "user")
        b.wait_present("#account-real-name:not([disabled])")
        b.wait_present("#account-locked[disabled]")
        b.wait_present("#account-set-password.disabled")
        b.wait_present("#account-delete.disabled")
        b.wait_present("#account-logout.disabled")
        b.wait_present("#account-role-checkbox-10[disabled]")
        b.wait_present("#account-role-checkbox-10:not(:checked)")
        b.wait_present('#account-real-name.disabled')

        # Try to change admins name
        b.go("account?id=admin")
        b.enter_page("account")
        b.wait_text("#account-user-name", "admin")
        b.wait_present("#account-real-name[disabled]")
        b.wait_present("#account-locked[disabled]")
        b.wait_present("#account-set-password.disabled")
        b.wait_present("#account-delete.disabled")
        b.wait_present("#account-logout.disabled")
        b.wait_present("#account-role-checkbox-10[disabled]")
        b.wait_present("#account-role-checkbox-10:checked")

        # Add role from the outside (and wait for it to stick)
        b.go("account?id=user")
        b.enter_page("account")
        b.wait_text("#account-user-name", "user")

        m.execute("usermod -a -G wheel user")
        b.wait_present("#account-role-checkbox-10:checked")

        b.relogin("account", "user")
        b.wait_text("#account-user-name", "user")

        # Try to change admins name again
        b.enter_page("account")
        b.go("account?id=admin")
        b.wait_text("#account-user-name", "admin")
        b.wait_present("#account-real-name:not([disabled])")
        b.wait_present("#account-locked:not([disabled])")
        b.wait_present("#account-set-password:not(.disabled)")
        b.wait_present("#account-delete:not(.disabled)")
        b.wait_present("#account-logout:not(.disabled)")
        b.wait_present("#account-role-checkbox-10:not([disabled])")
        b.wait_present("#account-role-checkbox-10:checked")

        b.set_val('#account-real-name', "Administratorrrr")

        b.go("account?id=admin")
        b.enter_page("account")
        b.wait_val("#account-real-name", "Administratorrrr")
        self.allow_restart_journal_messages()

    def testDynamic(self):
        m = self.machine
        b = self.browser

        m.execute("groupadd docker")

        # HACK - https://bugzilla.redhat.com/show_bug.cgi?id=1225957
        #
        # We compensate for the GFileMonitor bug by periodically
        # triggering them forcefully in the background.
        #
        # XXX - This is terrible and we should try hard to fix the
        # bug before merge.
        #
        # XXX - there is a race because of the two copies
        #
        if self.machine.os == "fedora-rawhide":
            self.machine.spawn("while true; do sleep 2; cp /etc/group /tmp/xxx && cp /tmp/xxx /etc/group; done", "passwd-trigger.log")

        self.login_and_go("accounts", href="/users/local")
        b.go("account?id=admin")

        b.wait_in_text("#account-change-roles-roles", "Container Administrator")
        b.wait_in_text("#account-change-roles-roles", "Container Administrator")

        # The roles dialog is live, removes entries even when open
        m.execute("groupdel docker")
        b.wait_not_in_text("#account-change-roles-roles", "Container Administrator")

test_main()
