#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

from testlib import *

class TestRoles(MachineCase):
    def testBasic(self):
        m = self.machine
        b = self.browser

        # Create a user without any role
        m.execute("useradd user -c 'User' || true")
        m.execute("echo foobar | passwd --stdin user")

        self.start_cockpit()

        def login(user, password):
            b.set_val("#login-user-input", user)
            b.set_val("#login-password-input", password)
            b.click('#login-button')

        # login
        b.open("server")
        b.wait_visible("#login")
        login("user", "foobar")
        b.expect_reload()
        b.wait_page("server")
        b.wait_text('#content-user-name', 'User')

        # HACK: Logging in as "user" will try to create a default
        # /var/lib/cockpit/machines file, but this will fail.
        # https://github.com/cockpit-project/cockpit/issues/1248
        self.allow_journal_messages("Can't write /var/lib/cockpit/machines: Failed to create file '/var/lib/cockpit/machines\\..*': Permission denied")

        # change its own name
        b.click('#content-user-name')
        b.click('a[onclick*="shell.go_login_account"]')
        b.wait_page("account")
        b.wait_text("#account-user-name", "user")
        b.wait_present("#account-real-name:not([disabled])")
        b.wait_present("#account-locked[disabled]")
        b.wait_present("#account-set-password.disabled")
        b.wait_present("#account-delete.disabled")
        b.wait_present("#account-logout.disabled")
        b.wait_present("#account-change-roles.disabled")
        b.wait_present("#account-change-roles.disabled")
        b.set_val('#account-real-name', "Userrrr")

        # Try to change admins name
        b.go("account?id=admin")
        b.wait_page("account")
        b.wait_text("#account-user-name", "admin")
        b.wait_present("#account-real-name[disabled]")
        b.wait_present("#account-locked[disabled]")
        b.wait_present("#account-set-password.disabled")
        b.wait_present("#account-delete.disabled")
        b.wait_present("#account-logout.disabled")
        b.wait_present("#account-change-roles.disabled")
        b.wait_present("#account-change-roles.disabled")

        # Add role from the outside (and wait for it to stick)
        b.go("account?id=user")
        b.wait_page("account")
        b.wait_text("#account-user-name", "user")
        b.wait_val("#account-real-name", "Userrrr")

        m.execute("usermod -a -G wheel user")
        b.wait_text("#account-roles", "Server Administrator")

        b.relogin("account", "user")

        # Try to change admins name again
        b.go("account?id=admin")
        b.wait_text("#account-user-name", "admin")
        b.wait_present("#account-real-name:not([disabled])")
        b.wait_present("#account-locked:not([disabled])")
        b.wait_present("#account-set-password:not(.disabled)")
        b.wait_present("#account-delete:not(.disabled)")
        b.wait_present("#account-logout:not(.disabled)")
        b.wait_present("#account-change-roles:not(.disabled)")
        b.wait_present("#account-change-roles:not(.disabled)")

        b.set_val('#account-real-name', "Administratorrrr")

        b.go("account?id=admin")
        b.wait_page("account")
        b.wait_val("#account-real-name", "Administratorrrr")
        self.allow_restart_journal_messages()

    def testDynamic(self):
        m = self.machine
        b = self.browser

        m.execute("groupadd docker")

        self.login_and_go("accounts")
        b.go("account?id=admin")

        b.click("#account-change-roles")
        b.wait_popup("account-change-roles-dialog")
        b.wait_in_text("#account-change-roles-roles", "Container Administrator")
        b.click("#account-change-roles-dialog button:contains('Cancel')")
        b.wait_popdown("account-change-roles-dialog")

        m.execute("groupdel docker")

        # Wait for the D-Bus client to have caught up with this change
        # TODO: This needs to be migrated away from the old dbus
        b.wait_js_func(
            """(function () {
            var client = shell.dbus();
            var roles = client.get("/com/redhat/Cockpit/Accounts", "com.redhat.Cockpit.Accounts").Roles;
            var has_docker = roles && roles.some(function (r) { return r[0] == "docker" });
            client.release();
            return roles && !has_docker;
            })""")

        b.click("#account-change-roles")
        b.wait_popup("account-change-roles-dialog")
        b.wait_not_in_text("#account-change-roles-roles", "Container Administrator")
        b.click("#account-change-roles-dialog button:contains('Cancel')")
        b.wait_popdown("account-change-roles-dialog")

test_main()
