#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

from testlib import *

class TestAccounts(MachineCase):
    def testBasic(self):
        b = self.browser
        m = self.machine

        self.login_and_go("accounts")

        # Add a user externally
        m.execute("useradd anton")
        m.execute("echo foobar | passwd --stdin anton")
        b.wait_in_text('#accounts-list', "anton")

        # Set a real name
        b.go("accounts&account?id=anton")
        b.wait_page("account")
        b.set_val('#account-real-name', "Anton Arbitrary")
        b.wait_dbus_prop('com.redhat.Cockpit.Account', 'RealName', "Anton Arbitrary")
        check("Anton Arbitrary" in m.execute("grep anton /etc/passwd"))

        # Delete it
        b.click('#account-delete')
        b.wait_popup('account-confirm-delete-dialog')
        b.click('#account-confirm-delete-apply')
        b.wait_popdown('account-confirm-delete-dialog')
        b.wait_page("accounts")
        b.wait_not_in_text('#accounts-list', "Anton Arbitrary")

        # Create a user from the UI
        b.click('#accounts-create')
        b.wait_popup('accounts-create-dialog')
        b.set_val('#accounts-create-user-name', "berta")
        b.set_val('#accounts-create-real-name', "Berta Bestimmt")
        b.set_val('#accounts-create-pw1', "foobar")
        b.set_val('#accounts-create-pw2', "foobar")
        b.click('#accounts-create-create')
        b.wait_popdown('accounts-create-dialog')
        b.wait_in_text('#accounts-list', "Berta Bestimmt")

        # Delete it externally
        m.execute("userdel berta")
        b.wait_not_in_text('#accounts-list', "Berta Bestimmt")

        # Create a locked user
        b.click('#accounts-create')
        b.wait_popup('accounts-create-dialog')
        b.set_val('#accounts-create-user-name', "jussi")
        b.set_val('#accounts-create-real-name', "Jussi Junior")
        b.set_val('#accounts-create-pw1', "foobar")
        b.set_val('#accounts-create-pw2', "foobar")
        b.set_val('#accounts-create-locked', "yes")
        b.click('#accounts-create-create')
        b.wait_popdown('accounts-create-dialog')
        b.wait_in_text('#accounts-list', "Jussi Junior")

        # Unlock it and make it an admin
        b.go("accounts&account?id=jussi")
        b.wait_page("account")
        b.set_val('#accounts-create-locked', "no")
        b.click('#account-change-roles')
        b.wait_popup('account-change-roles-dialog')
        b.set_checked('#account-role-checkbox-wheel', True)
        b.click('#account-change-roles-apply')
        b.wait_popdown('account-change-roles-dialog')
        check("jussi" in m.execute("grep wheel /etc/group"))

test_main()
