#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2015 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import os
import unittest

import avocadolib
from testlib import *

avocado_tests = ["checklogin-basic.py",
                 "checklogin-raw.py",
                ]

@unittest.skipIf("atomic" in os.environ.get("TEST_OS", ""), "atomic: missing avocado")
@unittest.skipIf("debian" in os.environ.get("TEST_OS", ""), "Debian: missing avocado")
class TestAvocadoSuite(MachineCase):

    def setUp(self):
        MachineCase.setUp(self)
        self.start_cockpit()

    def testAvocado(self):
        self.allow_journal_messages("Error receiving data: Connection reset by peer")
        avocadolib.prepare_avocado_tests(self.machine)

        if not avocadolib.run_avocado(machine=self.machine, avocado_tests=avocado_tests, print_failed=True):
            self.fail("avocado tests failed")

if __name__ == '__main__':
    test_main()
