#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2015 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

from testlib import *
import json
import os
import sys

class TestKubernetes(MachineCase):
    def setUp(self):
        MachineCase.setUp(self)
        m = self.machine
        m.execute("systemctl start etcd kube-apiserver kube-controller-manager docker kube-proxy kubelet")
        m.upload(["mock-k8s-tiny-app.json"], "/tmp")

    def testDashboard(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/kubernetes/cluster", host=None)
        b.wait_in_text("#node-list", "127.0.0.1")

        m.execute("kubectl create -f /tmp/mock-k8s-tiny-app.json")
        b.wait_in_text("#service-list", "mock")

        # Successfully deploy via dialog
        b.click("#deploy-app")
        b.wait_popup("deploy-app-dialog")
        b.upload_file("#deploy-app-manifest-file", "mock-k8s-tiny-app.json")
        b.set_val("#deploy-app-namespace", "mynamespace")
        b.dialog_complete("#deploy-app-dialog")
        b.wait_in_text("#service-list", "mynamespace")

        # Fail deploy via dialog
        b.click("#deploy-app")
        b.wait_popup("deploy-app-dialog")
        b.upload_file("#deploy-app-manifest-file", "mock-k8s-tiny-app.json")
        b.set_val("#deploy-app-namespace", "!!!!")
        b.dialog_complete("#deploy-app-dialog", result="fail")
        b.dialog_cancel("#deploy-app-dialog")

test_main()
