#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

from testlib import *

import time
import unittest

class TestExample(MachineCase):
    def testBasic(self):
        m = self.machine
        b = self.browser

        self.login_and_go("/system")
        b.wait_js_cond("$('#settings a').length != 0")

class TestSimple(unittest.TestCase):
    def testOne(self):
        time.sleep(1)
        self.assertTrue(True)
    def testTwo(self):
	self.assertFalse(True)

if __name__ == '__main__':
    test_main()
