#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

from testlib import *

class TestNetworking(MachineCase):

    def get_iface(self, m, mac):
        def getit():
            return m.execute("for f in /sys/class/net/*; do a=$(cat $f/address); if test \"$a\" == %s; then echo $(basename $f); fi; done" % mac)
        return wait(getit).strip();

    def testBasic(self):
        b = self.browser
        m = self.machine

        # Something strange is happening here.
        #
        # When hot-plugging the network interface below, it is
        # automatically recognized and NM will create a connection
        # settings object for it with path
        # /org/freedesktop/NetworkManager/Settings/1.  No file in
        # /etc/sysconfig/network-scripts exists for it.  The interface
        # will be activated automatically with those default settings.
        #
        # Calling 'Update' on that object will cause a file to be
        # created in /etc/sysconfig/network-scripts, the connection is
        # activated immediately (so that the actual IP address of the
        # network interface changes), the settings object disappears
        # from D-Bus, and a new object with the same id and uuid
        # appears at /org/freedesktop/NetworkManager/Settings/2.
        #
        # In order to avoid racing against this, we explicitly modify
        # the connection with nmcli so that NetworkManager settles
        # down.

        # TODO: Make this work with non-root
        #
        # See https://bugzilla.gnome.org/show_bug.cgi?id=707983 for
        # one issue.

        b.default_user = "root"

        self.login_and_go("networking")
        b.wait_in_text("#networking-interfaces", m.address)

        # Add interface, wait for it to be recognized and activated by
        # Network Manager, and switch to its page

        mac = "52:54:00:9e:00:ff"
        label = "test"
        m.execute("echo -e 'TYPE=Ethernet\nHWADDR=%s' >/etc/sysconfig/network-scripts/ifcfg-%s" % (mac, label))
        m.execute("nmcli c reload")
        iface = self.get_iface(m, m.add_netiface(mac));

        b.wait_in_text("#networking-interfaces", iface)
        b.wait_in_text("#networking-interfaces tr:contains('%s')" % iface, "bps")
        b.click("#networking-interfaces tr:contains('%s')" % iface)
        b.wait_page("network-interface")

        # Configure a manual IP address
        #
        b.wait_in_text("#network-interface", "IPv4")
        b.click("tr:contains('IPv4') button")
        b.wait_popup("network-ip-settings-dialog")
        b.click("#network-ip-settings-dialog a:contains('Manual')")
        b.click("#network-ip-settings-dialog tr:contains('Address') button:contains('Add')")
        b.set_val("#network-ip-settings-dialog table:contains('Address') td:first-child input", "1.2.3.4")
        b.click("#network-ip-settings-dialog button:contains('Apply')")
        b.wait_popdown("network-ip-settings-dialog")
        b.wait_in_text("#network-interface .panel:contains('%s')" % iface, "1.2.3.4/24")

        # Disconnect
        #
        b.click(".panel-heading:contains('%s') button:contains('Off')" % iface)
        b.wait_in_text("#network-interface-hw", "Disconnected")

        # Switch it back to "auto" from the command line and bring it
        # up again
        #
        id = "System %s" % label
        m.execute("nmcli c m '%s' ipv4.method auto" % id)
        m.execute("nmcli c m '%s' ipv4.addresses ''" % id)
        b.wait_in_text("#network-interface-connections", "Automatic (DHCP)")
        m.execute("nmcli c up '%s'" % id)
        b.wait_in_text("#network-interface-hw", "Active")

    def testBond(self):
        b = self.browser
        m = self.machine

        # TODO: Make this work with non-root

        b.default_user = "root"

        self.login_and_go("networking")
        b.wait_in_text("#networking-interfaces", m.address)

        # Add interfaces
        iface1 = self.get_iface(m, m.add_netiface('f1'));
        iface2 = self.get_iface(m, m.add_netiface('f2'));
        b.wait_in_text("#networking-interfaces", iface1)
        b.wait_in_text("#networking-interfaces", iface2)

        # Bond them
        b.click("button:contains('Add Bond')")
        b.wait_popup("network-bond-settings-dialog")
        b.set_val("#network-bond-settings-dialog tr:contains('Name') input", "tbond")
        b.set_checked("label:contains('%s') input" % iface1, True)
        b.set_checked("label:contains('%s') input" % iface2, True)
        b.click("#network-bond-settings-dialog button:contains('Apply')")
        b.wait_popdown("network-bond-settings-dialog")
        b.wait_in_text("#networking-interfaces", "tbond")

        # Activate the bond.  This will not activate any of the
        # slaves.
        b.click("#networking-interfaces tr:contains('tbond')")
        b.wait_page("network-interface")
        b.click(".panel-heading button:contains('On')")
        b.wait_in_text("#network-interface-hw", "Bond without active parts")

        # Activate iface1 externally and wait for the bond to become
        # active.
        m.execute("ifup %s" % iface1)
        b.wait_in_text("#network-interface-hw", "Active")

        # Delete the bond
        b.click("#network-interface button:contains('Delete')")
        b.wait_page("networking")
        b.wait_not_in_text("#networking-interfaces", "tbond")

    def testBridge(self):
        b = self.browser
        m = self.machine

        # TODO: Make this work with non-root

        b.default_user = "root"

        self.login_and_go("networking")
        b.wait_in_text("#networking-interfaces", m.address)

        # Add interfaces
        iface1 = self.get_iface(m, m.add_netiface('f1'));
        iface2 = self.get_iface(m, m.add_netiface('f2'));
        b.wait_in_text("#networking-interfaces", iface1)
        b.wait_in_text("#networking-interfaces", iface2)

        # Bridge them
        b.click("button:contains('Add Bridge')")
        b.wait_popup("network-bridge-settings-dialog")
        b.set_val("tr:contains('Interface') input", "tbridge")
        b.set_checked("label:contains('%s') input" % iface1, True)
        b.set_checked("label:contains('%s') input" % iface2, True)
        b.click("#network-bridge-settings-dialog button:contains('Apply')")
        b.wait_popdown("network-bridge-settings-dialog")
        b.wait_in_text("#networking-interfaces", "tbridge")

        # Activate the bridge.  This will not activate any of the
        # slaves.
        b.click("#networking-interfaces tr:contains('tbridge')")
        b.wait_page("network-interface")
        b.click(".panel-heading button:contains('On')")
        b.wait_in_text("#network-interface-hw", "Bridge without active ports")

        # Activate iface1 externally and wait for the bridge to become
        # active.
        m.execute("ifup %s" % iface1)
        b.wait_in_text("#network-interface-hw", "Active")

        # Delete the bridge
        b.click("#network-interface button:contains('Delete')")
        b.wait_page("networking")
        b.wait_not_in_text("#networking-interfaces", "tbridge")

test_main()
