#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

from testlib import *

class TestSession(MachineCase):
    def testBasic(self):
        m = self.machine
        b = self.browser

        self.allow_restart_journal_messages()
        # Might happen when killing the bridge.
        self.allow_journal_messages("localhost: dropping message while waiting for child to exit")

        # TODO: Make this work with non-root
        b.default_user = "root"

        def wait_session(should_exist):
            def cond():
                return should_exist == ("admin" in m.execute("loginctl list-sessions"))
            if should_exist:
                wait(cond)
            else:
                # HACK - sometimes the session gets stuck forever in
                #        state 'closing' with no processes.
                #        https://bugs.freedesktop.org/show_bug.cgi?id=89024
                try:
                    wait(cond)
                except:
                    raise RepeatThis("https://bugs.freedesktop.org/show_bug.cgi?id=89024")

        def kill_user_admin():
            # logind from systemd 208 is buggy, so we use systemd directly if it fails
            # https://bugs.freedesktop.org/show_bug.cgi?id=71092
            m.execute("loginctl kill-user admin || systemctl kill user-1000.slice")

        wait_session(False)

        # Login
        self.login_and_go("server", user="admin", href="/system/host")
        wait_session(True)

        # Logout
        b.logout()
        b.wait_visible("#login")
        wait_session(False)

        # Login again
        b.set_val("#login-user-input", "admin")
        b.set_val("#login-password-input", "foobar")
        b.click('#login-button')
        b.expect_reload()
        b.enter_page("server")
        wait_session(True)

        # Kill session from the outside
        kill_user_admin()
        wait_session(False)

        b.relogin("server", "admin")
        wait_session(True)

        # TODO: This doesn't work as non-root
        # Kill session from the inside
        # b.click('#content-user-name')
        # b.click('a[onclick*="cockpit.go_login_account"]')
        # b.enter_page("account")
        # b.wait_text("#account-user-name", "admin")
        # b.click("#account-logout")
        # wait_session(False)

test_main ()
