#!/bin/bash
# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

set -e

parallel --gnu --progress -j ${TEST_JOBS:-1} <<EOF
./check-dbus
./check-login
./check-dashboard
./check-menu
./check-shutdown-restart
./check-system-info
./check-realms
./check-connection
./check-services
./check-networking
./check-pages
./check-storage TestStorage.testBasic
./check-storage TestStorage.testMounting
./check-storage TestStorage.testDosParts
./check-storage TestStorage.testLuks
./check-storage TestStorage.testRaid
./check-storage TestStorage.testJobs
./check-storage TestStorage.testLvm
./check-storage TestStorage.testUsed
./check-storage TestStorage.testHidden
./check-storage TestStorage.testUnused
./check-journal
./check-journal-renderer
./check-terminal
./check-accounts
./check-session
./check-roles
./check-multi-machine
EOF

echo VERIFICATION PASSED
