#!/bin/bash
# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

set -e

LANG=C
export LANG

TEST_OS=${TEST_OS:-fedora-22}
TEST_ARCH=${TEST_ARCH:-x86_64}
export TEST_OS
export TEST_ARCH

if which "parallel" >/dev/null 2>/dev/null; then
  RUNNER="parallel --gnu -j ${TEST_JOBS:-1}"
else
  RUNNER="sh -e"
fi

$RUNNER <<EOF
./check-dbus
./check-login
./check-dashboard TestDashboard.testBasic
./check-dashboard TestDashboard.testEdit
./check-dashboard TestDashboard.testSetup
./check-menu
./check-shutdown-restart
./check-system-info
./check-realms
./check-connection
./check-services
./check-networking
./check-pages
./check-storage TestStorage.testBasic
./check-storage TestStorage.testMounting
./check-storage TestStorage.testDosParts
./check-storage TestStorage.testLuks
./check-storage TestStorage.testRaid
./check-storage TestStorage.testJobs
./check-storage TestStorage.testLvm
./check-storage TestStorage.testUsed
./check-storage TestStorage.testHidden
./check-storage TestStorage.testUnused
./check-storage TestStorage.testResize
./check-storage TestStorage.testIgnored
./check-journal
./check-terminal
./check-accounts
./check-session
./check-roles
./check-multi-machine
./check-reauthorize
./check-docker
./check-loopback
./check-kubernetes
EOF

echo VERIFICATION PASSED
