#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

from testlib import *

import re
import ast

class TestShutdownRestart(MachineCase):
    def setUp(self):
        # we need a static ip for this test
        MachineCase.setUp(self, macaddr='52:54:00:9e:00:F3')

    def testBasic(self):
        m = self.machine
        b = self.browser

        # HACK -https://bugzilla.redhat.com/show_bug.cgi?id=1278287
        m.execute("setenforce 0")

        self.login_and_go("/system")

        # Reboot
        m.reset_reboot_flag()
        b.click("#shutdown-group button.btn-danger")
        b.wait_popup("shutdown-dialog")
        b.wait_in_text("#shutdown-action", 'Restart')
        b.click("#shutdown-delay button")
        b.click("a.opt span:contains('No Delay')")
        b.click("#shutdown-action")
        b.switch_to_top()
        # we don't need to wait for the dialog to close here, just the disconnect
        b.wait_popup("disconnected-dialog")
        m.wait_reboot()
        self.login_and_go("/system")

        self.allow_restart_journal_messages()
        self.allow_journal_messages("Shutdown scheduled for .*")
        self.check_journal_messages()

        # Poweroff
        b.click("#shutdown-group span.caret")
        b.click("#shutdown-group a:contains('Shutdown')")
        b.wait_popup("shutdown-dialog")
        b.wait_in_text("#shutdown-action", 'Shutdown')
        b.click("#shutdown-delay button")
        b.click("a.opt span:contains('No Delay')")
        b.click("#shutdown-action")
        b.switch_to_top()
        # we don't need to wait for the dialog to close here, just the disconnect
        b.wait_popup("disconnected-dialog")
        m.wait_poweroff()

if __name__ == '__main__':
    test_main()
