#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

from testlib import *

import socket
import time

def inject_extras(browser):
    browser.eval_js("""
    dashboard_addresses = function () {
       var addresses = $('#dashboard-hosts .list-group-item').map(function(i,e) { return $(e).data("address"); }).get();
       return addresses;
    }
    """)

def get_webapp_machines(browser):
    wm = { }
    cockpit = browser.eval_js("return dashboard_addresses();")
    for i in range (0, len(cockpit)):
        wm[cockpit[i]] = i;
    return wm

def wait_dashboard_addresses(b, expected):
    b.wait_js_func(
        """(function (expected) {
        return expected.sort().toString() == dashboard_addresses().sort().toString();
        })""", expected)

def wait_machine_dropdown_addresses(b, expected):
    b.wait_js_func(
        """(function (expected) {
        var dropdown_items = $('#machine-dropdown [data-address]')
        var dropdown_addresses = dropdown_items.map(function (i,e) { return $(e).data("address"); }).get();
        return expected.sort().toString() == dropdown_addresses.sort().toString();
        })""", expected)

def add_machine(b, address):
    b.click('#dashboard-add')
    b.wait_popup('dashboard_setup_server_dialog')
    b.set_val('#dashboard_setup_address', address)
    b.wait_text('#dashboard_setup_next', "Next")
    b.click('#dashboard_setup_next')
    b.wait_text('#dashboard_setup_next', "Add host")
    b.click('#dashboard_setup_next')
    b.wait_text('#dashboard_setup_next', "Close")
    b.click('#dashboard_setup_next')
    b.wait_popdown('dashboard_setup_server_dialog')


class TestMultiMachine(MachineCase):
    def setUp(self):
        MachineCase.setUp(self)
        self.machine2 = self.new_machine()
        self.machine2.start()
        self.machine2.wait_boot()

        self.machine3 = self.new_machine()
        self.machine3.start()
        self.machine3.wait_boot()

    def tearDown(self):
        if self.runner and self.runner.wasSuccessful():
            self.check_journal_messages(self.machine2)
            self.check_journal_messages(self.machine3)
        MachineCase.tearDown(self)

    def testBasic(self):
        b = self.browser
        m1 = self.machine
        m2 = self.machine2
        m3 = self.machine3

        def kill_user_admin(machine):
            # logind from systemd 208 is buggy, so we use systemd directly if it fails
            # https://bugs.freedesktop.org/show_bug.cgi?id=71092
            machine.execute("loginctl kill-user admin || systemctl kill user-1000.slice")

        self.login_and_go("dashboard", href="dashboard/list", host=None)
        inject_extras(b)
        wait_dashboard_addresses (b, [ "localhost" ])

        add_machine(b, m2.address)
        wait_dashboard_addresses (b, [ "localhost", m2.address ])

        add_machine(b, m3.address)
        wait_dashboard_addresses (b, [ "localhost", m2.address, m3.address ])

        wm = get_webapp_machines(b)
        m1_index = wm["localhost"]+1
        m2_index = wm[m2.address]+1
        m3_index = wm[m3.address]+1

        # TODO: The concrete error message when killing the bridge and
        # session is not predictable.  So we just wait for any error
        # to appear without checking the precise text.  We print the
        # error message, to help with issue #606.
        #
        # https://github.com/cockpit-project/cockpit/issues/606

        kill_user_admin(m2)
        b.wait_attr('#dashboard-hosts a:nth-child(%d) img' % m2_index, 'src', 'images/server-error.png')

        kill_user_admin(m3)
        b.wait_attr('#dashboard-hosts a:nth-child(%d) img' % m3_index, 'src', 'images/server-error.png')

        b.click('#dashboard-hosts a:nth-child(%d)' % m2_index)
        b.wait_popup('reconnect-dialog')
        print b.text('#reconnect-dialog-problem')
        b.click('#reconnect-dialog-reconnect')
        b.wait_popdown('reconnect-dialog')
        b.wait_attr('#dashboard-hosts a:nth-child(%d) img' % m2_index, 'src', 'images/server-small.png')

        b.click('#dashboard-hosts a:nth-child(%d)' % m3_index)
        b.wait_popup('reconnect-dialog')
        print b.text('#reconnect-dialog-problem')
        b.click('#reconnect-dialog-reconnect')
        b.wait_popdown('reconnect-dialog')
        b.wait_attr('#dashboard-hosts a:nth-child(%d) img' % m3_index, 'src', 'images/server-small.png')

        self.allow_restart_journal_messages()
        self.allow_journal_messages(".*: .* host key for server is not known: .*",
                                    # Might happen when killing the bridge.
                                    "localhost: dropping message while waiting for child to exit",
                                    "Received message for unknown channel: .*",
                                    ".*: error reading from ssh",
                                    ".*: bridge program failed: Child process exited with code .*")

    def testExternalPage(self):
        b = self.browser
        m1 = self.machine
        m2 = self.machine2

        # Modify the terminals to be different on the two machines.
        m1.execute("gunzip -c /usr/share/cockpit/system/terminal.min.html.gz | sed -e 's|</body>|magic-m1-token</body>|' > /usr/share/cockpit/system/terminal.min.html")
        m2.execute("gunzip -c /usr/share/cockpit/system/terminal.min.html.gz | sed -e 's|</body>|magic-m2-token</body>|' > /usr/share/cockpit/system/terminal.min.html")

        self.login_and_go("dashboard", href="dashboard/list", host=None)
        inject_extras(b)
        add_machine(b, m2.address)
        wait_dashboard_addresses (b, [ "localhost", m2.address ])

        # Switch to the shell and wait for it to also notice m2.
        b.leave_page()
        wait_machine_dropdown_addresses(b, [ "localhost", m2.address ])

        # Once the shell knows about m2, we can navigate to it.
        b.go("/@%s/system/terminal" % m2.address)
        b.enter_page("/system/terminal", host=m2.address)
        b.wait_present("body")
        b.wait_in_text("body", "magic-m2-token")

        b.leave_page()
        b.go("/@localhost/system/terminal")
        b.enter_page("/system/terminal")
        b.wait_present("body")
        b.wait_in_text("body", "magic-m1-token")

test_main()
