#!/usr/bin/env python

import argparse
import sys

sys.dont_write_bytecode = True

import testinfra

def main():
    parser = argparse.ArgumentParser(description='Manually trigger CI Robots')
    parser.add_argument('-f', '--force', action="store_true",
                        help='Force setting the status even if the program logic thinks it shouldn''t be done')
    parser.add_argument('pull', help='The pull request to trigger')
    parser.add_argument('context', help='The github task context to trigger')
    opts = parser.parse_args()

    github = testinfra.GitHub()

    if opts.context not in testinfra.DEFAULT_VERIFY:
        sys.stderr.write("github-trigger: invalid context: {0}\n".format(opts.context))
        return 2

    sys.stderr.write("triggering pull {0} for context {1}\n".format(opts.pull, opts.context))
    pull = github.get("pulls/" + opts.pull)

    # triggering is manual, so don't prevent triggering a user that isn't on the whitelist
    # but issue a warning in case of an oversight
    login = pull["head"]["user"]["login"]
    if login not in github.whitelist:
        sys.stderr.write("warning: pull request author '{0}' isn't in github-whitelist.\n".format(login))

    revision = pull['head']['sha']
    statuses = github.statuses(revision)
    status = statuses.get(opts.context, { })
    if status.get("state", "empty") not in ["empty", "error", "failure"]:
        if opts.force:
            sys.stderr.write("Pull request isn't in error state, but forcing update.\n")
        else:
            sys.stderr.write("Pull request isn't in error state. Status is: '{0}'\n".format(status["state"]))
            return 1

    changes = { "state": "pending", "description": testinfra.NOT_TESTED, "context": opts.context }
    github.post("statuses/" + revision, changes)
    return 0

if __name__ == '__main__':
    sys.exit(main())
