#!/bin/bash
# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

set -e

SELF="make-rpms"
. ./testlib.sh

usage()
{
	echo >&2 "usage: $SELF"
}

mock_opts=""
mock_clean_opts="--no-clean --no-cleanup-after"
args=$(getopt -o "h,v,c" -l "help,verbose,clean" -- "$@")
eval set -- "$args"
while [ $# -gt 0 ]; do
	case $1 in
	--clean)
                # We always use --no-cleanup-after because a
                # --no-clean build can not start with a chroot that
                # has been cleaned previously.
		mock_clean_opts="--no-cleanup-after"
		;;
	-v|--verbose)
		mock_opts="$mock_opts --verbose"
		;;
	-h|--help)
		usage
		exit 0
		;;
	--)
		shift
		break
		;;
	esac
	shift
done

if [ $# -ne 0 ]; then
	usage
	exit 2
fi

if test $(id -u) = 0; then
    echo "Don't run this as root!"
    exit 1
fi

make_srpm=$(dirname "$0")/make-srpm
if [ ! -x "$make_srpm" ]; then
  make_srpm=make-srpm
fi

os=$TEST_OS
arch=$TEST_ARCH
EXTRA_FLAGS=${EXTRA_FLAGS:-}

srpm=$("$make_srpm" "$@")
rm -rf mock

# Create our custom config
mkdir mock
cp --preserve=timestamps /etc/mock/site-defaults.cfg mock/
cp --preserve=timestamps /etc/mock/logging.ini mock/
cp --preserve=timestamps /etc/mock/$os-$arch.cfg mock/$os-$arch-cockpit.cfg
cat >>mock/$os-$arch-cockpit.cfg <<EOF
config_opts['root'] = "$os-$arch-cockpit"
config_opts['yum.conf'] += """
[updates-testing]
enabled=1
"""
EOF
# HACK: Signatures seem to be unreliable in Fedora 21 right now
sed -i -e 's/gpgcheck=1/gpgcheck=0/' mock/$os-$arch-cockpit.cfg
touch -r /etc/mock/$os-$arch.cfg mock/$os-$arch-cockpit.cfg

if /usr/bin/mock $mock_opts $mock_clean_opts --configdir=mock/ \
	--resultdir mock -r $os-$arch-cockpit $srpm \
	--define="extra_flags $EXTRA_FLAGS"; then
    grep "^Wrote: .*\.\($arch\|noarch\)\.rpm$" mock/build.log | while read l; do
        p=$(basename "$l") # knocks off the "Wrote:" part as well...
        echo $p
        mv mock/$p .
    done
    exit 0
else
    echo >&2 FAILED
    exit 1
fi
