#!/bin/sh
# install/upgrade RPMs that apply to OSTree
set -eu

cd /var/tmp/

# Note: cockpit-selinux would be desirable, but needs setroubleshoot-server which isn't installed
rpm-ostree install --cache-only cockpit-bridge-*.rpm \
    cockpit-networkmanager-*.rpm cockpit-system-*.rpm cockpit-tests-*.rpm

# run cockpit/ws once to generate certificate; avoids slow down on every start
podman container runlabel INSTALL cockpit/ws
