#! /bin/bash

set -e

create_images=
make_rpms_opts=

while [ $# -gt 0 ]; do
    case $1 in
	--clean)
	    create_images=t
            make_rpms_opts="--clean"
	    ;;
    esac
    shift
done

IP=/sbin/ip

silent()
{
  "$@" > /dev/null 2> /dev/null
  return $?
}

# Prerequisites
require_binary() {
  bin=$1
  if ! which "$bin" >/dev/null 2>/dev/null; then
    echo 1>&2 "Missing tool /usr/bin/$bin"
    exit 1
  fi
}
require_binary trickle

if ! silent $IP address show dev cockpit0; then
  sudo ./vm-prep
fi

if [ -z "$create_images" ]; then
    ./vm-download -f cockpit
    ./vm-download -f ipa
fi

skip="cockpit-doc-
cockpit-debuginfo"

rpms=$(../tools/make-rpms $make_rpms_opts | grep -vF "$skip")
if [ -z "$rpms" ]; then
  exit 1
fi

if [ -n "$create_images" ]; then
    ./vm-reset
    ./vm-create -v -f cockpit
    unset TEST_DATA
    ./vm-save -f cockpit
fi

./vm-reset
./vm-install -f cockpit $rpms
