#!/usr/bin/env python
# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

# vm-create  -- Make a root image suitable for use with vm-run.
#
# Usage: vm-create
#
# Installs the OS indicated by TEST_OS and TEST_ARCH into the image
# for test machine TEST_IMAGE and tweaks it to be useable with
# vm-run and testlib.py.

import argparse
import subprocess
import sys

import testvm

parser = argparse.ArgumentParser(description='Create a virtual machine image')
parser.add_argument('-v', '--verbose', action='store_true', help='Display verbose progress details')
parser.add_argument('-f', '--flavor', action='store', help='The flavor to create')
parser.add_argument('-F', '--force', action='store_true', help='Always create image from scratch')
parser.add_argument('-n', '--no-save', action='store_true', help='Don\'t save the new image')
parser.add_argument('args', nargs='*', help='Arguments to the flavor setup script')
args = parser.parse_args()

def download_image(flavor):
    try:
        subprocess.check_call([ "./vm-download", "--flavor", flavor ])
        return True
    except:
        return False

try:
    machine = testvm.QemuMachine(verbose=args.verbose, flavor=args.flavor)
    if args.force or machine.needs_build():
        if args.force or not download_image(args.flavor):
            machine.build(args.args)
            if not args.no_save:
                machine.save()
except testvm.Failure, ex:
    print >> sys.stderr, "vm-create:", ex
    sys.exit(1)
