#!/bin/sh
# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

VIRSH=/bin/virsh
QEMU_BRIDGE_HELPER=/usr/libexec/qemu-bridge-helper

SELF=vm-prep
. ./testlib.sh

set -euf

usage()
{
	echo >&2 "usage: $SELF [-u]"
}

prepare()
{
	if silent $VIRSH net-info cockpit; then
		$VIRSH net-destroy cockpit
		$VIRSH net-undefine cockpit
	fi

	# HACK: NetworkManager races with dnsmasq-dhcp on bridge
	# https://bugzilla.redhat.com/show_bug.cgi?id=1205081
	cat > /etc/sysconfig/network-scripts/ifcfg-cockpit0 << EOF
DEVICE=cockpit0
NM_CONTROLLED=no
EOF

	$VIRSH net-define ./network-cockpit.xml

	$VIRSH net-autostart cockpit
	$VIRSH net-start cockpit

	if [ ! -u $QEMU_BRIDGE_HELPER ]; then
		chmod -v u+s $QEMU_BRIDGE_HELPER
	fi

	qemu_config_dir=
	for d in /etc/qemu-kvm/ /etc/qemu; do
	    if test -f ${d}/bridge.conf; then
		qemu_config_dir=${d}
	    fi
	done
	if test -z "$qemu_config_dir"; then
	    warning "Could not find qemu config dir"
	    exit 1
	fi

	rule="allow cockpit0"
	if ! silent grep -F cockpit0 ${qemu_config_dir}/bridge.conf; then
		echo "$rule" >> ${qemu_config_dir}/bridge.conf
	fi
}

unprepare()
{
	if ! silent virsh net-info cockpit; then
		warning "the cockpit network has not been configured"
		exit 1
	fi

	$VIRSH net-destroy cockpit
	$VIRSH net-undefine cockpit
}

operation=prepare
args=$(getopt -o "uh" -l "help" -- "$@")
eval set -- "$args"
while [ $# -gt 0 ]; do
	case $1 in
	-h|--help)
		usage
		exit 0
		;;
	-u)
		operation=unprepare
		;;
	--)
		shift
		break
		;;
	esac
	shift
done

if [ $# -ne 0 ]; then
	usage
	exit 2
fi

uid=$(id -u)
if [ "$uid" != "0" ]; then
	warning "this script must be run as root"
	exit 1
fi

$operation
