#!/bin/sh

set -eu
cd "$(realpath -m "$0"/../../..)"

message() { printf "  %-8s %s\n" "$1" "$2" >&2; }

# bundle the current state of HEAD
(
    head_sha="$(git rev-parse HEAD)"
    head_pack="tmp/${head_sha}.pack"
    if [ ! -f "${head_pack}" ]; then
        message 'BUNDLE' "${head_pack}  [HEAD]"
        # include the latest tag so that git-describe works
        latest_tag="$(git describe --abbrev=0 HEAD)"
        git bundle create --quiet "${head_pack}" HEAD ${latest_tag}
    fi
    echo "# ${head_pack}"
    echo "echo '=== Unpacking cockpit'"
    echo "git -c advice.detachedHead=false clone ${head_pack} cockpit"
)

# bundle the node_modules from our cache so the container doesn't need
# to download them (since it has no network access)
(
    GITHUB_REPO='node-cache'
    SUBDIR='node_modules'
    V=0
    . tools/git-utils.sh
    node_sha="$(get_index_gitlink node_modules)"
    node_pack="tmp/${node_sha}.pack"
    if [ ! -f "${node_pack}" ]; then
        fetch_sha_to_cache "${node_sha}"
        message 'BUNDLE' "${node_pack}  [node_modules]"
        git_cache bundle create --quiet "${node_pack}" "sha-${node_sha}"
    fi
    echo "# ${node_pack}"
    echo "echo '=== Unpacking node_modules'"
    echo "git -c advice.detachedHead=false clone -b sha-${node_sha} ${node_pack} cockpit/node_modules"
    echo "echo '=== Copying package-lock.json'"
    echo "make -C cockpit -f pkg/build package-lock.json"
)

# if the tree isn't clean, make a stash and send it in, too.  we do this
# separately from HEAD, because we can send the stash as a thin pack.
(
    # `git stash create -u` doesn't work properly, so check for untracked files
    # and warn.  This can be removed (and -u added below) when that's supported.
    untracked="$(git ls-files -o --exclude-standard)"
    if [ -n "${untracked}" ]; then
        printf '\nThe following untracked files will be excluded:\n%s\n\n' "${untracked}" >&2
    fi
    stash_sha="$(git stash create)"
    if [ -n "${stash_sha}" ]; then
        stash_pack="tmp/${stash_sha}.pack"
        message 'BUNDLE' "${stash_pack}  [stash]"
        # we can't include raw commits, so use a temporary tag
        git tag "stash-${stash_sha}" "${stash_sha}" >/dev/null
        git bundle create --quiet "${stash_pack}" "stash-${stash_sha}" "^HEAD"
        git tag --delete "stash-${stash_sha}" >/dev/null
        echo "# ${stash_pack}"
        echo "echo '=== Unpacking stash'"
        echo "git -C cockpit bundle unbundle ../${stash_pack}"
        echo "git -C cockpit stash apply --quiet ${stash_sha}"
    fi
)

# if dist/ is up to date, then include it
(
    if pkg/build -q -o package-lock.json; then
        dist_tar="tmp/dist.tar"
        message 'TAR' "${dist_tar}"
        tar cf "${dist_tar}" dist
        echo "# ${dist_tar}"
        echo "echo '=== Unpacking dist/'"
        echo "tar xm -C cockpit dist < ${dist_tar}"
    fi
)

echo "rm -rf tmp"
