#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2016 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import parent
from testlib import *

class TestDevices(MachineCase):
    def testBasic(self):
        b = self.browser
#        m = self.machine

        self.login_and_go("/devices")
        b.wait_in_text("caption", "PCI Devices - by Class")
        
        b.wait_timeout(10)
        b.wait_present("th")
        b.wait_in_text("body", "Ethernet controller") # means initial data load passed

    def testUnplug(self):
        b = self.browser
#        m = self.machine

        self.login_and_go("/devices")
        b.wait_timeout(10)
        b.wait_present("th")
        b.click("th:contains('USB controller')") # click on the row header
#        b.snapshot("snapshot")
        # TODO: click Unbind, confirm, check for empty driver

if __name__ == '__main__':
    test_main()
