#!/usr/bin/python3

# This file is part of Cockpit.
#
# Copyright (C) 2015 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import parent
from storagelib import *
from testlib import *


@nondestructive
class TestStorageIgnored(StorageCase):

    def testIgnored(self):
        m = self.machine
        b = self.browser

        self.login_and_go("/storage")
        disk = self.add_ram_disk()
        b.wait_in_text("#drives", disk)

        m.execute(f"yes | mke2fs -q -L TEST {disk}")
        with b.wait_timeout(30):
            b.wait_in_text("#mounts", disk)

        # Hide it via a udev rule
        m.execute("mkdir -p /run/udev/rules.d")
        m.write("/run/udev/rules.d/99-ignore.rules",
                'SUBSYSTEM=="block", ENV{ID_FS_LABEL}=="TEST", ENV{UDISKS_IGNORE}="1"\n')
        self.addCleanup(m.execute, "rm /run/udev/rules.d/99-ignore.rules; udevadm control --reload; udevadm trigger")
        m.execute("udevadm control --reload; udevadm trigger")
        b.wait_not_in_text("#mounts", disk)


if __name__ == '__main__':
    test_main()
