#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/../common/pywrap", sys.argv)

# This file is part of Cockpit.
#
# Copyright (C) 2015 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

from storagelib import StorageCase
from testlib import test_main


class TestStorageScaling(StorageCase):

    def testScaling(self):
        m = self.machine
        b = self.browser

        m.execute("modprobe scsi_debug num_tgts=200")

        self.login_and_go("/storage")
        with b.wait_timeout(60):
            b.click("#drives button:contains(Show all 202 drives)")
            b.wait_not_in_text("#drives", "Show all")
            b.wait_js_cond('ph_select("#drives .sidepanel-row").length == 202')


if __name__ == '__main__':
    test_main()
