#!/usr/bin/python3

# This file is part of Cockpit.
#
# Copyright (C) 2020 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import unittest
import subprocess

import parent
from testlib import *


class TestTestLib(unittest.TestCase):

    def testTestCategorization(self):
        def compareOutput(cmd, *args):
            blocks = set(frozenset(block.split("\n")) for block in subprocess.check_output(cmd).strip().decode().split("\n\n"))
            self.assertEqual(blocks, set(args))

        compareOutput(["test/verify/check-example", "-l", "TestPersistentExample", "TestSimple"],
                      frozenset(["TestSimple.testOne", "TestSimple.testThree", "TestSimple.testTwo"]),
                      frozenset(["TestPersistentExample.testOne", "TestPersistentExample.testTwo"]))

        compareOutput(["test/verify/check-example", "-l", "TestSimple.testOne", "TestPersistentExample.testOne"],
                      frozenset(["TestSimple.testOne"]), frozenset(["TestPersistentExample.testOne"]))

if __name__ == '__main__':
    test_main()
