#!/usr/bin/python3
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import parent
from testlib import *

class TestMenu(MachineCase):
    @enableAxe
    def testBasic(self):
        b = self.browser
        m = self.machine

        # Add a link with a hash in it to test that this works
        m.execute("mkdir -p /usr/local/share/cockpit/systemd && cp -rp /usr/share/cockpit/systemd/* /usr/local/share/cockpit/systemd")
        m.execute("""sed -i '/"menu"/a "memory": { "label": "Memory", "path": "#/memory" },' /usr/local/share/cockpit/systemd/manifest.json""")

        self.login_and_go("/system")

        b.switch_to_top()
        b.click('#navbar-dropdown')
        b.wait_visible('a[data-target="#about"]')
        b.click('a[data-target="#about"]')
        b.wait_popup('about')
        b.click('#about button[data-dismiss="modal"]')
        b.wait_popdown("about")

        self.check_axe("Test-navigation")

        # Check that we can use a link with a hash in it (fixed in Cockpit 170)
        if m.image != 'rhel-7-5-distropkg':
            b.switch_to_top()
            b.click("a[href='/system/#/memory']")
            b.enter_page("/system")
            b.wait_visible("#memory_status")

if __name__ == '__main__':
    test_main()
