#!/usr/bin/python3

# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import sys
import time
import unittest

import parent
from testlib import *


@skipPackage("example")
class TestExample(MachineCase):

    def testFail(self):
        self.login_and_go("/system")
        self.assertFalse(True)

    def testBasic(self):
        self.login_and_go("/system")


class TestSimple(unittest.TestCase):

    def testOne(self):
        for i in range(0, 10):
            time.sleep(0.100)
            if i % 2:
                sys.stderr.write(">1%i\n" % i)
            else:
                print(">2", i)
        self.assertTrue(True)

    def testTwo(self):
        self.assertFalse(True)

    def testThree(self):
        self.assertTrue(True)


if __name__ == '__main__':
    test_main()
