#!/usr/bin/env python
# This file is part of Cockpit.
#
# Copyright (C) 2015 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import argparse
import os
import shutil
import sys
import imp

basepath = os.path.join(os.path.dirname(os.path.abspath(__file__)),"..")
if not basepath in sys.path:
    sys.path.insert(1, basepath)
from common import testinfra
vminstall = imp.load_source('vminstall', os.path.join(basepath,"vm-install"))
vmdownload = imp.load_source('vmdownload', os.path.join(basepath,"vm-download"))

image_list="ipa openshift fedora-stock"

parser = argparse.ArgumentParser(
        description='Prepare testig environment, download images and build and cinstall cockpit',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
parser.add_argument('-v', '--verbose', action='store_true', help='Display verbose progress details')
parser.add_argument('-n', '--noinstall', action='store_true', help='Do not install cockpit to base image')
parser.add_argument('-f', '--force', action='store_true', help='Force update of images')
parser.add_argument('image', nargs='?', default=testinfra.DEFAULT_IMAGE, help='The image to use')
args = parser.parse_args()

test_os = args.image
build_os = test_os

if test_os == "fedora-atomic":
    build_os = "fedora-23"
elif test_os == "rhel-atomic":
    build_os = "rhel-7"

# vm-reset replacement
shutil.rmtree("%s/tmp/run" % basepath)
os.makedirs("%s/tmp/run" % basepath)

vmdownload.download_images(set((test_os, build_os)), args.force, [])
vmdownload.download_images(image_list.split(" "), args.force, [])

if args.noinstall:
    print "Not installing cockpit to base image"
else:
    args.sit = False
    args.containers = False
    args.quick = False
    vminstall.build_and_install(test_os, build_os, args)

