upstream_project_url: https://github.com/cockpit-project/cockpit
specfile_path: cockpit.spec
actions:
  # create-archive does not work with multiple sources, so do the spec mangling ourselves
  post-upstream-clone:
    # we already build a spec file with correct Version, so extract it
    - |
      bash -exc '
      mapfile -t TARBALLS < <(tools/make-dist)
      # Extract spec file from main tarball (first in array)
      tar -xJf "${TARBALLS[0]}" --wildcards "*/tools/cockpit.spec" --strip-components=2
      # Move all tarballs to current directory for packit
      mv "${TARBALLS[@]}" .
      '

  fix-spec-file:
    # packit needs local file names, not URLs
    - sed -i 's|^\(Source[0-9]*:\s*\).*\/|\1|' cockpit.spec

srpm_build_deps:
  - automake
  - asciidoctor
  - gcc
  - gettext
  - glib2-devel
  - jq
  - make
  - nodejs
  - systemd-devel

# use the nicely formatted release NEWS from our upstream release, instead of git shortlog
copy_upstream_release_description: true

jobs:
  - job: tests
    identifier: self
    trigger: pull_request
    targets: &test_targets
      centos-stream-9-x86_64:
        distros: ["centos-stream-9", "CentOS-Stream-9-image-mode"]
      centos-stream-9-aarch64: {}
      centos-stream-10-x86_64:
        distros: ["centos-stream-10", "CentOS-Stream-10-image-mode"]

  # run build/unit tests on test targets
  - job: copr_build
    trigger: pull_request
    targets: *test_targets
