upstream_project_url: https://github.com/cockpit-project/cockpit
actions:
  post-upstream-clone:
    # packit will overwrite the version in its "fix spec file" stage
    - tools/create-spec --version 0 --build-all -o cockpit.spec tools/cockpit.spec.in
  create-archive:
    # The sandcastle doesn't have enough ram to run webpack, so wait
    # until the webpack-jumpstart workflow has run and grab the result.
    - tools/webpack-jumpstart --wait --rebase
    - tools/make-dist
srpm_build_deps:
  - automake
  - gcc
  - glib2-devel
  - make
  - systemd-devel
# use the nicely formatted release NEWS from our upstream release, instead of git shortlog
copy_upstream_release_description: true
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-35
      - fedora-36
      - fedora-development
      - centos-stream-8-x86_64
      - centos-stream-9-x86_64

  # run build/unit tests on some interesting architectures
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        # 32 bit
        - fedora-development-i386
        # big-endian
        - fedora-development-s390x

  - job: copr_build
    trigger: release
    metadata:
      owner: "@cockpit"
      project: "cockpit-preview"
      preserve_project: True
      targets:
      - fedora-35
      - fedora-36
      - fedora-development
      - centos-stream-8-x86_64
      - centos-stream-9-x86_64
    actions:
      post-upstream-clone:
        # HACK: https://github.com/packit/packit/issues/1560
        - tools/node-modules checkout
        # packit will overwrite the version in its "fix spec file" stage
        - tools/create-spec --version 0 --build-all -o cockpit.spec tools/cockpit.spec.in
      # HACK: tarball for releases (copr_build, koji, etc.), copying spec's Source0; this
      # really should be the default, see https://github.com/packit/packit-service/issues/1505
      create-archive:
        - sh -exc "curl -L -O https://github.com/cockpit-project/cockpit/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
        - sh -exc "ls ${PACKIT_PROJECT_NAME_VERSION}.tar.xz"

  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches:
        - fedora-development
        - fedora-35
        - fedora-36

  - job: koji_build
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-development
        - fedora-35
        - fedora-36

  - job: bodhi_update
    trigger: commit
    metadata:
      dist_git_branches:
        # rawhide updates are created automatically
        - fedora-35
        - fedora-36
