upstream_project_url: https://github.com/cockpit-project/cockpit
specfile_path: cockpit.spec
actions:
  post-upstream-clone:
    # build patched spec
    - tools/node-modules make_package_lock_json
    - cp tools/cockpit.spec .
    # packit will compute and set the version by itself
    - tools/fix-spec ./cockpit.spec 0

  create-archive:
    - tools/make-dist

srpm_build_deps:
  - automake
  - gcc
  - gettext
  - glib2-devel
  - make
  - nodejs
  - npm
  - systemd-devel
# use the nicely formatted release NEWS from our upstream release, instead of git shortlog
copy_upstream_release_description: true
jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - centos-stream-8-x86_64

  - job: tests
    identifier: self
    trigger: pull_request
    targets:
      - centos-stream-8-x86_64
