specfile_path: cockpit.spec
actions:
  post-upstream-clone:
    # the upstream git spec file has unresolved macros which are normally put
    # in at `make dist` time; they are not important for CI
    # also, build optional packages for CentOS 8
    - sh -c 'sed "s/%{npm-version:.*}/0/; s/build_optional 0/build_optional 1/" tools/cockpit.spec > cockpit.spec'
  create-archive:
    # this is being triggered immediately on a pull_request event; wait for
    # build-dist.yml to generate the dist tarball
    - tools/webpack-jumpstart --wait
    - ./autogen.sh --disable-polkit --disable-ssh --disable-pcp --with-systemdunitdir=/invalid CPPFLAGS=-Itools/mock-build-env PKG_CONFIG_PATH=tools/mock-build-env
    - make XZ_OPT=-0 dist
    - sh -c 'echo cockpit-*.tar.xz'
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-33
      - fedora-34
      - centos-stream-8-x86_64
