#! /bin/bash

. ./test/testlib.sh

set -x

# Create new tarballs in ./test

( cd test
  ./vm-create -v -f cockpit
  ./vm-pack -f cockpit
  ./vm-create -v -f ipa
  ./vm-pack -f ipa
)

# Test it.

( export TEST_DATA=$PWD/test
  ./VERIFY || ./VERIFY || ./VERIFY
)

echo "Tarball test/cockpit-$TEST_OS-$TEST_ARCH.tar.gz is ready for use."
