#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# This file is part of Cockpit.
#
# Copyright (C) 2017 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

DAYS = 7

import argparse
import sys
import time

sys.dont_write_bytecode = True

import task

def main():
    parser = argparse.ArgumentParser(description="Ensure necessary issue exists for translations")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    opts = parser.parse_args()

    task.verbose = opts.verbose
    text = "Update translations from Fedora Zanata"

    since = time.time() - (DAYS * 86400)
    issue = task.issue(text, text, "po-refresh", None, state="all", since=since)

    if issue:
        sys.stderr.write("#{0}: po-refresh\n".format(issue["number"]))

if __name__ == '__main__':
    sys.exit(main())
