= cockpit-desktop(1)

== Name

cockpit-desktop - Cockpit Desktop integration

== Synopsis

*cockpit-desktop* _URLPATH_ [_SSH_HOST_]

== Description

The *cockpit-desktop* program provides secure access to Cockpit pages
in an already running desktop session. It starts a web server
(*cockpit-ws*) and a web browser in an isolated network namespace, and
a *cockpit-bridge(8)* in the running user session.

This avoids having to log into Cockpit, and having to enable
*cockpit.socket* system-wide. The network isolation ensures that no
other user, and not even other processes in the user's session, can
access this local web server.

*URLPATH* is the Cockpit page to open, i. e. the path component of
Cockpit URLs. It is highly recommended to only open a
https://cockpit-project.org/guide/latest/embedding.html[particular page frame], not the entire Cockpit navigation and menu. For example, the
path `+/cockpit/@localhost/storage/index.html+` will open the Storage
page. It is also possible to give abbreviated forms of urls, such as
"`+/storage+`" or "`+/network/firewall+`".

_SSH_HOST_ is an optional SSH remote host specification (_hostname_
or _username@hostname_). If given, *cockpit-bridge* will be started
on the remote host through *ssh(1)* instead, i. e. the Cockpit web
browser will show that remote host. Note that this is more of an
experimental/demo feature.

== Environment

The *BROWSER* environment variable specifies the browser command (and
possibly options) that will be used to open the requested Cockpit page.
If not set, *cockpit-desktop* attempts to use an internal minimalistic
WebKit browser, and failing that, will attempt to detect some reasonable
alternatives.

== Bugs

include::partials/bugs.adoc[]

== Author

include::partials/author.adoc[]

== See also

*cockpit-ws(8)*, *cockpit-bridge(1)*
