= cockpit.js: Spawning Processes

This is the API for spawning a process and receiving its output, as well
as exit codes.

[[cockpit-spawn-exec]]
== cockpit.exec()

....
process = cockpit.exec(program, opts, [positionals], [options])
....

Spawns a process on the system with structurally safe argument
construction.

The key design principle: flags and subcommands (`+opts+`) are separated
from the values the command operates on (`+positionals+`). A `+--+`
separator is automatically inserted before positionals, preventing
dynamic values from being interpreted as flags.

`+program+`::
  The executable name or path, as a string.

`+opts+`::
  An array of flags, subcommands, and flag+value tuples. Each element
  may be:
  - A flag string: `+"-f"+`, `+"--lock"+`, or a template literal like
    `+`--date=${d}`+`
  - A subcommand string: `+"commit"+`, `+"report"+`, `+"restart"+`
  - A pair `+[flag, value]+` for flags that take one argument:
    `+["--shell", shell]+`
  - A triple `+[flag, value, value]+` for flags that take two arguments:
    `+["--bind", src, dest]+`
+
In TypeScript, flag strings must have a statically known first character
(a literal or template literal starting with `+-+` or `+--+`).
Subcommand strings must start with a non-`+-+` character. This prevents
dynamic user-controlled values from being used as flags.

`+positionals+`::
  An optional array of strings that the command operates on — filenames,
  usernames, device paths, mount targets, etc. A `+--+` separator is
  automatically inserted before these values.

`+options+`::
  An optional javascript plain object. Accepts all the same fields as
  link:#cockpit-spawn-spawn[`+cockpit.spawn()+`]: `+"binary"+`,
  `+"directory"+`, `+"err"+`, `+"environ"+`, `+"pty"+`, `+"batch"+`,
  `+"latency"+`, and `+"superuser"+`.

=== Examples

Simple command with a flag and a positional:

....
cockpit.exec("passwd", ["-S"], [username],
             { superuser: "require", environ: ["LC_ALL=C"] })
....

Flag that takes a value, using a tuple:

....
cockpit.exec("usermod", [["--shell", newShell]], [username],
             { superuser: "require" })
....

Template literal flag (the flag name is statically known):

....
cockpit.exec("date", [`--date=${datestr}`], ["+%s"])
....

Building opts dynamically:

....
const opts = ["--create-home", ["-s", shell]];
if (real_name)
    opts.push(["-c", real_name]);
cockpit.exec("useradd", opts, [username], { superuser: "require" })
....

Command with no positionals — just omit the argument:

....
cockpit.exec("uname", ["-r"])
....

Command with no flags — pass an empty array:

....
cockpit.exec("cat", [], [filename])
....

Running a shell command — the shell code is a flag value:

....
cockpit.exec("sh", [["-c", shellCommand]])
....

=== Commands with non-standard argument parsing

This API assumes POSIX option conventions (`+getopt+`, `+--+`). Most
commands work fine, but some need alternative approaches:

tar (dashless flags with arguments)::
  Won't work: `+cockpit.exec("tar", [["xvf", archive]])+`
  +
  Recommended: `+cockpit.exec("tar", ["-xv", ["-f", archive]])+`
  (POSIX style)

ps (BSD-style flags)::
  Won't work: `+cockpit.exec("ps", [["ut", tty]])+`
  +
  Recommended: `+cockpit.exec("ps", ["-u", ["-t", tty]])+`
  (POSIX style)

echo (does not support `+--+`)::
  Won't work: `+cockpit.exec("echo", [], [msg])+`
  +
  But you wouldn't ever spawn echo from cockpit anyway.

test / [ (expression grammar, not getopt)::
  Works: `+cockpit.exec("test", ["!", ["-f", path], "-a", [path, "-nt", other]])+`
  +
  The binary file operators (`+-ef+`, `+-nt+`, `+-ot+`) are
  special-cased as `+[string, operator, string]+` triples.

git (dynamic non-flag values before `+--+`)::
  Works: `+cockpit.exec("git", [["-C", dir], "commit"])+`
  +
  For dynamic non-flag values before `+--+`, use `+is_not_flag()+`:
+
....
cockpit.assert(cockpit.is_not_flag(rev));
cockpit.exec("git", ["log", rev], ["file1", "file2"])
....

flock (`+-c+` is a special-case positional)::
  `+flock+` expects `+flock [options] file -c command+`, where `+-c+` comes
  after the file. Put both the file and `+-c command+` in positionals:
  `+cockpit.exec("flock", ["-o"], ["/tmp/lockfile", "-c", "echo locked"])+`

find (dangerous — avoid!)::
  `+find+` has very few actual options (`+-H+`, `+-L+`, `+-P+`).
  Everything else (`+-name+`, `+-exec+`, `+-delete+`, ...) is part of a
  positional expression language. There is no way to separate filenames
  from expressions like `+-delete+` and `+-exec+`, which are interpreted
  even after `+--+`. Avoid `+find+` entirely; use
  link:#cockpit-file[`+cockpit.file()+`] or filesystem APIs instead.

=== cockpit.is_not_flag()

....
cockpit.is_not_flag(value)
....

A type guard that checks whether a dynamic string starts with a
printable ASCII character other than `+-+`. After calling
`+cockpit.assert(cockpit.is_not_flag(value))+`, the value can be used as
a subcommand in the `+opts+` array.

[[cockpit-spawn-spawn]]
== cockpit.spawn()

WARNING: `+cockpit.spawn()+` is deprecated. Use
link:#cockpit-spawn-exec[`+cockpit.exec()+`] instead. The `+spawn()+`
API makes it too easy to pass dynamic strings where flags are expected,
leading to argument injection vulnerabilities.

....
process = cockpit.spawn(args, [options])
....

Spawns a process on the system.

The `+args+` should be an array starting with the executable and
containing all the arguments to pass on the command line. If `+args+` is
a string then it is interpreted as an executable name. The optional
`+options+` argument is a javascript plain object and can contain any of
the following fields:

`+"binary"+`::
  If set to `+true+` then handle the input and output of the process as
  arrays of binary bytes.
`+"directory"+`::
  The directory to spawn the process in.
`+"err"+`::
  Controls where the standard error is sent. By default it is logged to
  the journal. If set to `+"out"+` it is included in with the output
  data. If set to `+"ignore"+` then the error output is discarded. If
  set to `+"message"+`, then it will be returned as the error message.
  When the `+"pty"+` field is set, this field has no effect.
`+"environ"+`::
  An optional array that contains strings to be used as additional
  environment variables for the new process. These are `+"NAME=VALUE"+`
  strings.
`+"pty"+`::
  Launch the process in its own PTY terminal, and send/receive terminal
  input and output.
`+"batch"+`::
  Batch data coming from the process in blocks of at least this size.
  This is not a guarantee. After a short timeout the data will be sent
  even if the data doesn't match the batch size. Defaults to zero.
`+"latency"+`::
  The timeout for flushing any cached data in milliseconds.
`+"superuser"+`::
  Set to `+"require"+` to spawn the process as root instead of the
  logged in user. If the currently logged in user is not permitted to
  become root (eg: via `+pkexec+`) then the `+client+` will immediately
  be link:#cockpit-dbus-onclose[closed] with a `+"access-denied"+`
  problem code.
  +
  Set to `+"try"+` to try to run the process as root, but if that fails,
  fall back to an unprivileged process.

The spawned process is a
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[promise]
that will complete if the process exits successfully, or fail if there's
a problem. Some additional methods besides the standard promise methods
are documented below.

The standard output of the process is made available via the spawned
process object. Any non-UTF8 output from the process will be coerced
into textual form. It is highly recommended that only textual output be
produced by the command. The standard error is logged to the journal.

[[cockpit-spawn-script]]
== cockpit.script()

....
process = cockpit.script(script, [args], [options])
....

Run a shell script on the system.

This function link:#cockpit-spawn-spawn[spawns] a Bourne shell script
process. The full text of the `+/bin/sh+` shell script should be passed
in as the first argument. The `+args+` can be an array of arguments, not
including the executable, which are passed to the script as `+$1+`,
`+$2+` and so on. Shebang options are not used or respected.

The `+options+` is an optional javascript plain object and can include
any of the fields listed for the
link:#cockpit-spawn-spawn[`+cockpit.spawn()+`] function.

The spawned process is a
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[promise]
that will complete if the script exits successfully, or fail if there's
a problem. Some additional methods besides the standard promise methods
are documented below.

The standard output of the process is made available via the spawned
process object. Any non-UTF8 output from the process will be coerced
into textual form. It is highly recommended that only textual output be
produced by the command. The standard error is logged to the journal by
default.

[[cockpit-spawn-then]]
== process.then()

....
process.then((data[, message]) => { ... })
....

This is a standard
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[promise]
method. It sets up a handler to be called when the process finishes
successfully.

The `+data+` argument contains the standard output of the process. If it
a string, unless the process was opened in binary mode, in which case
the `+data+` is an array of bytes. If a `+process.stream()+` handler is
set up, then any standard output data consumed by the handler will not
be included in the `+data+` argument.

If the process was spawned with the `+"err"+` option set to
`+"message"+` then the second argument will contain the standard error
output of the process.

[[cockpit-spawn-catch]]
== process.catch()

....
process.catch((exception[, data]) => { ... })
....

This is a standard
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[Promise]
method. It sets up a handler to be called when the process fails,
terminates or exits.

The `+exception+` object passed to the handler can have the following
fields:

`+message+`::
  A message describing the exception. If the process was spawned with
  the `+"err"+` option set to `+"message"+` then the second argument
  will contain the standard error output of the process.
`+problem+`::
  A link:#cockpit-problems[problem code] string when a problem occurred
  starting or communicating with the process. This is `+null+` if the
  process exited or was terminated.
`+exit_status+`::
  The numeric exit status of the process. This is `+null+` if the
  process did not exit.
`+exit_signal+`::
  A string representing a unix signal that caused the process to
  terminate. This is `+null+` if the process did not terminate because
  of a signal.

If the process actually ran and produced output before failing, it will
be available in the `+data+` argument. Otherwise this argument will be
`+undefined+`.

[[cockpit-spawn-stream]]
== process.stream()

....
process.stream(data => { ... })
....

This sets up a handler to be called when the process has standard
output. The handler will be called multiple times. The handler will be
called regardless of whether the process ends up exiting successfully or
not.

Only one handler may be registered at a time. Registering an additional
handler replaces the previous one. The handler receives either string
`+data+` or an array of binary bytes as its argument. A stream handler
may return a number, which indicates the number of characters or bytes
consumed from `+data+`. Any data not consumed will be included again the
next time the handler is called.

If a `+process.stream()+` handler is set up, then the `+process.then()+`
handlers will only get any remaining data not consumed by the stream
handler.

[[cockpit-spawn-input]]
== process.input()

....
process.input(data, [stream])
....

This method writes `+data+` to the standard input of the process. If
`+data+` is `+null+` or `+undefined+` it is not sent. The `+data+`
should be a string or an array of bytes if the process was opened in
binary mode.

If `+stream+` is set to `+true+` then this function may be called again
with further input. Otherwise the standard input of the process is
closed.

[[cockpit-spawn-close]]
== process.close()

....
process.close([problem])
....

Close the process by closing its standard input and output. If
`+problem+` is specified it should be a standard
link:#cockpit-problems[problem code] string. In this case the process
will be terminated with a signal.
