#! /bin/bash

set -e

# remove cockpit distro packages, testing with upstream master
rpm --erase --verbose cockpit cockpit-ws cockpit-bridge cockpit-system

/var/lib/testvm/fedora.install --rhel "$@"

# HACK: work around https://bugzilla.redhat.com/show_bug.cgi?id=1624862
rm /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-AUX-2018

# HACK: work around https://bugzilla.redhat.com/show_bug.cgi?id=1637875: net.ifnames=0 is ignored
touch /etc/udev/rules.d/80-net-setup-link.rules
dracut --force
