#! /bin/bash

set -e

# remove cockpit distro packages, testing with upstream master
# subscription-manager-cockpit needs these, thus --nodeps
rpm --erase --nodeps --verbose cockpit cockpit-ws cockpit-bridge cockpit-system

/var/lib/testvm/fedora.install --rhel "$@"

# HACK: https://bugzilla.redhat.com/show_bug.cgi?id=1782435
# segfaults at boot and breaks every test due to unexpected messages
rm /usr/libexec/virt-what-cpuid-helper
