[[feature-storaged]]
== storaged

If available on the system, Cockpit uses
https://github.com/storaged-project/storaged/[`storaged`] to configure
and monitor storage, disks, mounts etc. on the system. This
functionality is present in the Cockpit _storaged_ package.

The `storaged` project is originally based on a project called
https://www.freedesktop.org/wiki/Software/udisks/[`udisks`] and added
support for many more features such as
https://en.wikipedia.org/wiki/Logical_Volume_Manager_(Linux)[LVM],
https://en.wikipedia.org/wiki/ISCSI[iSCSI],
https://en.wikipedia.org/wiki/Linux_DM_Multipath[Multipath], and
https://btrfs.wiki.kernel.org/index.php/Main_Page[BTRFS]. The same tools
and backwards compatible API are available between `storaged` and
`udisks` the projects. Cockpit can use `udisks` but disables many of
it's storage related features, including updating `/etc/fstab` and
`/etc/crypttab` for stability reasons.

For non root users, storaged controls access to its APIs via
link:#privileges[Policy Kit] and a user logged into Cockpit will have
the same permissions as they do from the command line.

To perform similar tasks from the command line, use the `storagedctl`
command:

....
$ udisksctl dump
...
....

To perform LVM tasks, you may use the various LVM commands, such as
`vgcreate`, `lvresize` and so on. Cockpit will detect such changes made
at the command line.

Cockpit recognizes devices with multiple paths and can start the
`multipathd` service in case it is not running. On the command line, you
can control multipath features with the `mpathconf`, `multipathd`, and
`multipath` commands.

To manage iSCSI initiators from the command line, you can use `iscsiadm`
and related tools.
