= cockpit(1)
:doctype: manpage
:manmanual: cockpit
:mansource: cockpit

[[cockpit-name]]
== Name

cockpit - Cockpit

[[cockpit-synopsis]]
== Description

Cockpit is a web accessible interactive admin interface for Linux
machines. Cockpit can usually be accessed on port `+9090+` of the
machine it's installed on. Cockpit starts on demand. Use your system
credentials to log in.

[[cockpit-components]]
== Components

The *cockpit-ws* web service listens on port `+9090+` and is started
on demand by *systemd*. The Cockpit web service authenticates the
user, loads Cockpit into the browser, and starts *cockpit-bridge* in a
Linux user session.

The *cockpit-bridge* provides Cockpit in the web browser with access
to the system APIs. It does this over its standard in and standard out.
The bridge is started like a shell once per Linux user session.

[[cockpit-bugs]]
== Bugs
include::partials/bugs.adoc[]

[[cockpit-author]]
== Author
include::partials/author.adoc[]

[[cockpit-also]]
== See also

*cockpit-tls(8)* , *cockpit.bridge(1)* , *systemd(1)*, *https://cockpit-project.org/guide/latest[Cockpit guide]*
