#!/bin/sh -eu

# Check for mistakes in tarball distribution

find $1/dist $1/pkg -name '*.gz' -print | tee /dev/stderr | sort | while read file; do
        echo "Refusing to distribute gzip files" >&2
        exit 1
done
