#!/bin/sh -euf

set -euf

# Just a handy script to install a WIP cockpit on a machine somewhere

BASE=$(dirname $0)
SKIP="cockpit-doc-
cockpit-debuginfo-
cockpit-test-assets
cockpit-selinux-policy-"
RPMS=$($BASE/make-rpms | grep -vF "$SKIP" | tr '\n' ' ')

scp $RPMS $1:
ssh $1 "set -x && sudo dnf --assumeyes reinstall $RPMS && sudo systemctl restart cockpit"
