#!/bin/sh

GITHUB_BASE='allisonkarlitskaya'
GITHUB_REPO='ferny'
SUBDIR='modules/ferny'

V="${V-0}" # default to friendly messages

set -eu
cd "${0%/*}/.."
. tools/git-utils.sh

# we default to check out the node_modules corresponding to the gitlink in the index
sha="${1-$(get_index_gitlink "${SUBDIR}")}"

# fetch by sha to prevent us from downloading something we don't want
fetch_sha_to_cache "${sha}"

# we're actually going to do this; let's remove the old one
rm -rf "modules/ferny"
git submodule deinit "modules/ferny"
rm -rf -- "$(git rev-parse --absolute-git-dir)/modules/ferny"

# and check out the new one
# we need to use the tag name here, unfortunately
clone_from_cache "${sha}"
