#!/bin/bash
# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

set -eu

if [ $# -gt 1 ]; then
    echo "usage: make-srpm [tarball]" >&2
    exit 2
fi

# When running in an external make this breaks our use
# of make in the make-srpm lib tool and make_dist.py

export MAKEFLAGS=
export MAKELEVEL=
export MFLAGS=

base=$(cd $(dirname $0)/..; pwd -P)

if [ -z ${1-} ]; then
    source=$("$base/test/make_dist.py" | tail -n1)
else
    source="$1"
fi

version=$(echo "$source" | sed -n 's|.*cockpit-\([^ /-]\+\)\.tar\..*|\1|p')
if [ -z "$version" ]; then
    echo "make-srpm: couldn't parse version from tarball: $source"
    exit 2
fi

# We actually modify the spec so that the srpm is standalone buildable
modify_spec() {
sed -e "/^Version:.*/d" -e "1i\
%define wip wip\nVersion: $version\n"
}

tmpdir=$(mktemp -d $PWD/srpm-build.XXXXXX)
tar xaf "$source" -O cockpit-$version/tools/cockpit.spec | modify_spec > $tmpdir/cockpit.spec

# on RHEL/CentOS 8 (only), cockpit is delivered as two mostly identical source packages.
# "cockpit" with build_basic=1, and "cockpit-appstream" with build_optional=1
# the spec has proper build_* defaults depending on the Name:
if grep -qE '^ID=.*(rhel|centos)' /etc/os-release && grep -qE '^VERSION_ID="8' /etc/os-release; then
    sed '/^Name:/ s/$/-appstream/' < $tmpdir/cockpit.spec > $tmpdir/cockpit-appstream.spec
fi

RPMNAMES=""

for spec in $tmpdir/*.spec; do
    rpmbuild -bs \
             --quiet \
             --define "_sourcedir $(dirname $source)" \
             --define "_specdir $tmpdir" \
             --define "_builddir $tmpdir" \
             --define "_srcrpmdir `pwd`" \
             --define "_rpmdir $tmpdir" \
             --define "_buildrootdir $tmpdir/.build" \
             $spec
     RPMNAMES="$RPMNAMES $(rpm --qf '%{Name}-%{Version}-%{Release}.src.rpm\n' -q --specfile $spec | head -n1)"
done

rm -rf $tmpdir
echo "$RPMNAMES"
