#!/usr/bin/env node

var fs, po2json, Jed;

function fatal(message, code) {
    console.log("po2json: " + message);
    process.exit(code || 1);
}

function usage() {
    console.log("usage: po2json [--module] input output");
    process.exit(2);
}


try {
    fs = require('fs');
    po2json = require('po2json');
    Jed = require('jed');
} catch(ex) {
    fatal(ex.message, 127); /* missing looks for this */
}

var argi = 2;
var module = false;

if (process.argv[argi] == "--module") {
    module = true;
    argi++;
}

if (process.argv.length != argi + 2) {
    usage();
}

var input = process.argv[argi];
var output = process.argv[argi + 1];

function prepare_header(header) {
    var body, statement, plurals = header["plural-forms"], ret = null;
    if (plurals) {
        try {
            /* Check that the plural forms isn't being sneaky since we build a function here */
            Jed.PF.parse(plurals);
        } catch(ex) {
            fatal("bad plural forms: " + ex.message, 1);
        }

        /* A function for the front end */
	statement = header["plural-forms"];
        if (statement[statement.length - 1] != ';')
            statement += ';';
	body = '\nvar nplurals, plural;\n' + statement + '\nreturn plural;';
	ret = new Function("n", body);

        /* Added back in later */
        delete header["plural-forms"];
    }

    /* We don't need to be transferring this */
    delete header["project-id-version"];
    delete header["report-msgid-bugs-to"];
    delete header["pot-creation-date"];
    delete header["po-revision-date"];
    delete header["last-translator"];
    delete header["language-team"];
    delete header["mime-version"];
    delete header["content-type"];
    delete header["content-transfer-encoding"];

    return ret;
}

po2json.parseFile(input, { "fuzzy": true }, function(err, jsonData) {
    var plurals, pos;

    if (err)
        fatal(err.message);

    var header = jsonData[""];
    if (header)
        plurals = prepare_header(header);

    var data = JSON.stringify(jsonData);

    /* We know the brace in is the location to insert our function */
    if (plurals) {
        pos = data.indexOf('{', 1);
        data = data.substr(0, pos + 1) + "'plural-forms':" + String(plurals) + "," + data.substr(pos + 1);
    }

    if (module)
        data = "define(" + data + ");";

    fs.writeFile(output, data, function(err) {
        if (err)
	    fatal(err.message);
    });
});
