#!/bin/bash
# This file is part of Cockpit.
#
# Copyright (C) 2016 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.
set -ex

# HACK: docker falls over regularly, print its log if it does
systemctl start docker || journalctl -u docker

mkdir /var/tmp/images/kubernetes/rpms
cp -r /var/tmp/build-results/*.rpm /var/tmp/images/kubernetes/rpms/

cd /var/tmp/images/kubernetes/
docker build --build-arg VERSION=wip -t cockpit/kubernetes .
rm -r /var/tmp/images/kubernetes/rpms

rm -rf /var/log/journal/* || true
