#!/bin/bash
# This file is part of Cockpit.
#
# Copyright (C) 2016 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.
set -ex

# HACK: docker falls over regularly, print its log if it does
systemctl start docker || journalctl -u docker

for NAME in kubernetes registry
do
    mkdir "/var/tmp/containers/$NAME/rpms"
    cp -r /var/tmp/build-results/*.rpm "/var/tmp/containers/$NAME/rpms/"
    cd "/var/tmp/containers/$NAME/"
    docker build --build-arg VERSION=wip -t "cockpit/$NAME" .
    rm -r "/var/tmp/containers/$NAME/rpms"
done

rm -rf /var/log/journal/* || true
