'\" t
.\"     Title: cockpit
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2025-07-29
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "COCKPIT" "1" "2025-07-29" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.sp
cockpit
.sp
cockpit
.sp
1
.sp
cockpit
.sp
Cockpit
.SH "DESCRIPTION"
.sp
Cockpit is a web accessible interactive admin interface for Linux
machines. Cockpit can usually be accessed on port \f(CR9090\fP of the
machine it\(cqs installed on. Cockpit starts on demand. Use your system
credentials to log in.
.SH "COMPONENTS"
.sp
The \f(CRcockpit\-ws\fP web service listens on port \f(CR9090\fP and is started
on demand by \f(CRsystemd\fP. The Cockpit web service authenticates the
user, loads Cockpit into the browser, and starts \f(CRcockpit\-bridge\fP in a
Linux user session.
.sp
The \f(CRcockpit\-bridge\fP provides Cockpit in the web browser with access
to the system APIs. It does this over its standard in and standard out.
The bridge is started like a shell once per Linux user session.
.SH "BUGS"
.sp
Please send bug reports to either the distribution bug tracker or the
\c
.URL "https://github.com/cockpit\-project/cockpit/issues/new" "upstream bug
tracker" .
.SH "AUTHOR"
.sp
Cockpit has been written by many
.URL "https://github.com/cockpit\-project/cockpit/" "contributors" "."
.SH "SEE ALSO"
.sp
Cockpit Guide
.sp
cockpit\-ws
.sp
8
.sp
cockpit\-bridge
.sp
1
.sp
cockpit.conf
.sp
5
.sp
systemd
.sp
1