name: build-ws-container
on:
  # auto-refresh every Monday morning
  schedule:
    - cron: '0 2 * * 1'
  # can be run manually on https://github.com/cockpit-project/cockpit/actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    environment: quay.io
    permissions: {}
    timeout-minutes: 20
    env:
      RUNC: docker
      PLATFORMS: linux/amd64,linux/arm64

    steps:
      - name: Set up Docker to use containerd image store to support multi-arch images
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU to support multi-arch images
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx to support multi-arch images
        uses: docker/setup-buildx-action@v3

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Dockerfile  must correspond to latest release, not main
      - name: Check out latest tag
        run: |
          git checkout $(git rev-list --tags --max-count=1)
          git describe

      - name: Log into container registry
        run: $RUNC login -u ${{ secrets.QUAY_BOTUSER }} -p ${{ secrets.QUAY_TOKEN }} quay.io

      - name: Build and push ws container
        run: containers/ws/release.sh
