# doc: https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme
---

name: Differential ShellCheck
on:
  pull_request:
    branches: [main, rhel-*]

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v3
        with:
          severity: warning
          token: ${{ secrets.GITHUB_TOKEN }}
