name: flatpak-test
on:
  pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: none
    timeout-minutes: 20
    steps:
      - name: Install required build and test dependencies
        run: sudo apt install -y --no-install-recommends autoconf automake elfutils libglib2.0-dev libsystemd-dev xsltproc xmlto flatpak-builder xvfb cockpit-system

      - name: Configure flathub remote
        run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # need this to also fetch tags
          fetch-depth: 0

      - name: Minimum configuration for building dist tarball
        run: |
          ./autogen.sh --disable-polkit --disable-ssh --disable-pcp --with-systemdunitdir=/invalid CPPFLAGS=-Itools/mock-build-env PKG_CONFIG_PATH=tools/mock-build-env

      - name: Build and install flatpak
        run: sh -x containers/flatpak/install --user --install-deps-from=flathub

      - name: Smoke-test the installed flatpak
        run: |
          . /etc/profile.d/flatpak.sh
          xvfb-run dbus-run-session sh -ec '
            containers/flatpak/test/test-ssh
            containers/flatpak/test/test-browser
          '
