name: verify-antora
on:
  pull_request:
    # Only run when a file has changed in doc/ directory
    # Or the workflow file was changed
    paths:
      - doc/**
      - .github/workflows/verify-antora.yml
    branches:
      - main
jobs:
  verify-antora:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
            version: 10

      - name: Setup Node with Cache
        uses: actions/setup-node@v7
        with:
          node-version: 'latest'
          cache: 'pnpm'
          cache-dependency-path: '**/.github/workflows/*.yml'

      - name: Verify Antora can build
        run: pnpx antora antora-playbook.yml

      - name: Show generated Antora files
        run: tree doc/output/antora/ -h
