name: webpack-jumpstart
on:
  pull_request_target:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: none
    timeout-minutes: 20
    env:
      MERGE_SHA: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
    steps:
      - name: Build jumpstart tarball
        run: |
          id="$(docker container create -u node -w /home/node node /bin/sh -c \
            'git init cockpit &&
             cd cockpit &&
             git fetch --depth 1 https://github.com/cockpit-project/cockpit "'"${MERGE_SHA}"'":build &&
             git checkout build &&
             pkg/build webpack-jumpstart.tar -j$(nproc)'
          )"

          docker container start --attach "${id}" >&2
          docker container cp "${id}":/home/node/cockpit/webpack-jumpstart.tar .
          docker container rm -f "${id}"

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: webpack-jumpstart
          path: webpack-jumpstart.tar
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: none
    environment: cockpit-dist
    timeout-minutes: 5
    env:
      GIT_DIR: git-dir.git
      MERGE_SHA: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
    steps:
      - name: Set up work area
        run: |
            set -ux

            git init -b main

            git config user.name "GitHub Workflow"
            git config user.email "cockpituous@cockpit-project.org"

            git remote add cache "ssh://git@github.com/${GITHUB_REPOSITORY%/*}/cockpit-dist"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: webpack-jumpstart
          path: artifact

      - name: Stage git commit
        run: |
          set -ux
          mkdir worktree
          tar -C worktree -x --exclude '.git*' dist package-lock.json < artifact/webpack-jumpstart.tar
          git --work-tree worktree add dist package-lock.json
          git --work-tree worktree commit --quiet -m "Build for ${MERGE_SHA}"
          rm -rf worktree

          git tag "sha-${HEAD_SHA}"

      - name: Push git commit
        run: |
          eval $(ssh-agent)
          ssh-add - <<< '${{ secrets.DEPLOY_KEY }}'
          git push cache tag "sha-${HEAD_SHA}"
          ssh-add -D
          ssh-agent -k
